version: '3.3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: sujiakeji-rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: dev
      RABBITMQ_DEFAULT_PASS: dev

  sidecar:
    image: sujiakeji/sujiakeji-sidecar
    container_name: sujiakeji-sidecar
    depends_on:
      - rabbitmq
    ports:
      - 9200:9200
    environment:
      EUREKA_SERVER_HOST: sujiakeji-eureka-server
      EUREKA_SERVER_PORT: 9000
      SIDECAR_HOST: sujiakeji-sidecar-js
      SIDECAR_PORT: 11100
      SPRING_PROFILES_ACTIVE: dev
